# Generated by Django 3.2.9 on 2021-12-01 10:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivateChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('users', models.ManyToManyField(help_text='users in a private chat', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PrivateRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_accepted', models.BooleanField(default=False)),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('from_user', models.ForeignKey(help_text='user who send request', on_delete=django.db.models.deletion.CASCADE, related_name='send_request', to=settings.AUTH_USER_MODEL)),
                ('to_user', models.ForeignKey(help_text='user who receive request', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receive_request', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PrivateMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_text', models.CharField(max_length=2000, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('private_chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat_private.privatechat')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
