# Generated by Django 3.2.9 on 2021-12-04 15:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat_private', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='privatechat',
            name='users',
        ),
        migrations.AddField(
            model_name='privatechat',
            name='user_1',
            field=models.ForeignKey(help_text='first user in a private chat', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='first_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='privatechat',
            name='user_2',
            field=models.ForeignKey(help_text='second user in a private chat', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='second_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
