# Generated by Django 3.2.9 on 2021-11-28 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('private_chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='privatemessage',
            name='message_text',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
